// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGOWKi9hr_wFTBet4KNdNuBSgU8MJxLRs',
    appId: '1:569026003826:web:3703c52129f48fe59c53eb',
    messagingSenderId: '569026003826',
    projectId: 'bright-brush',
    authDomain: 'bright-brush.firebaseapp.com',
    storageBucket: 'bright-brush.firebasestorage.app',
    measurementId: 'G-G5WRNTXXTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3zA-TXn-R1JbzTTwUcJasb1btFOoB7Uk',
    appId: '1:569026003826:android:2c01f0f3cd7ff3909c53eb',
    messagingSenderId: '569026003826',
    projectId: 'bright-brush',
    storageBucket: 'bright-brush.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9rKstZHSfJfK8Osyhk7tjvcBHFaJcBpY',
    appId: '1:569026003826:ios:71ec2097c78324459c53eb',
    messagingSenderId: '569026003826',
    projectId: 'bright-brush',
    storageBucket: 'bright-brush.firebasestorage.app',
    iosBundleId: 'com.example.brightbrush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9rKstZHSfJfK8Osyhk7tjvcBHFaJcBpY',
    appId: '1:569026003826:ios:71ec2097c78324459c53eb',
    messagingSenderId: '569026003826',
    projectId: 'bright-brush',
    storageBucket: 'bright-brush.firebasestorage.app',
    iosBundleId: 'com.example.brightbrush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGOWKi9hr_wFTBet4KNdNuBSgU8MJxLRs',
    appId: '1:569026003826:web:91865d46cded1b179c53eb',
    messagingSenderId: '569026003826',
    projectId: 'bright-brush',
    authDomain: 'bright-brush.firebaseapp.com',
    storageBucket: 'bright-brush.firebasestorage.app',
    measurementId: 'G-SMNM1F1VSK',
  );
}
